#!/usr/bin/env python3
"""Generate prompts/profile/{types,chapters} and src/ai/profile/embedded.rs from the research doc.

Source: docs/superpowers/specs/2026-07-21-ai-profile-chapters-research.md
Run from the repo root: python3 scripts/gen_profile_prompts.py
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs/superpowers/specs/2026-07-21-ai-profile-chapters-research.md")
TYPES_DIR = os.path.join(ROOT, "prompts/profile/types")
CHAPTERS_DIR = os.path.join(ROOT, "prompts/profile/chapters")
EMBED = os.path.join(ROOT, "src/ai/profile/embedded.rs")

# Canonical taxonomy order (must match registry::TYPE_KEYS).
ORDER = ["corporate", "smb-services", "product", "ecommerce", "personal", "media-news",
         "expert-content", "nonprofit", "government", "institution", "portal-directory",
         "events-culture", "general"]


def parse_doc(text):
    types = {}
    cur = None
    for block in re.split(r"(?m)^# TYPE: ", text):
        block = block.strip()
        if not block or block.startswith("AI Profile") or block.startswith("Consolidated"):
            # skip the document preamble (first split chunk)
            if "\n## names" not in block:
                continue
        key = block.splitlines()[0].strip()
        if key not in ORDER:
            continue
        names = {}
        m = re.search(r"## names\n(.*?)\n## ", block, re.S)
        if m:
            for line in m.group(1).splitlines():
                if ":" in line:
                    k, v = line.split(":", 1)
                    names[k.strip()] = v.strip()
        m = re.search(r"## classifier_description\n(.*?)\n## chapters", block, re.S)
        desc = m.group(1).strip() if m else ""
        chapters = []
        chap_block = block.split("## chapters", 1)[1] if "## chapters" in block else ""
        for cb in re.split(r"(?m)^### ", chap_block)[1:]:
            lines = cb.splitlines()
            cid = lines[0].strip()
            fields = {}
            for field in ("heading_en", "target_chars", "selection_focus", "synthesis_instructions"):
                fm = re.search(r"(?m)^%s:\s*(.*)$" % field, cb)
                if fm:
                    fields[field] = fm.group(1).strip()
            chapters.append((cid, fields))
        types[key] = {"names": names, "desc": desc, "chapters": chapters}
    return types


def max_pages_for(target_chars):
    return max(4, min(20, round(target_chars / 450)))


def write_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    with open(SRC, encoding="utf-8") as f:
        text = f.read()
    types = parse_doc(text)
    missing = [k for k in ORDER if k not in types]
    if missing:
        sys.exit("Missing types in research doc: %s" % missing)

    embed_types = []
    embed_chapters = []
    for key in ORDER:
        t = types[key]
        write_file(os.path.join(TYPES_DIR, key + ".md"),
                   "---\nname_cs: %s\nname_en: %s\n---\n%s\n" %
                   (t["names"].get("cs", key), t["names"].get("en", key), t["desc"]))
        embed_types.append((key, "../../../prompts/profile/types/%s.md" % key))
        for cid, fields in t["chapters"]:
            tc = int(fields["target_chars"])
            body = ("---\nheading: %s\ntarget_chars: %d\nmax_pages: %d\n---\n"
                    "## selection_focus\n%s\n\n## synthesis_instructions\n%s\n" %
                    (fields["heading_en"], tc, max_pages_for(tc),
                     fields["selection_focus"], fields["synthesis_instructions"]))
            write_file(os.path.join(CHAPTERS_DIR, key, cid + ".md"), body)
            embed_chapters.append((key, cid, "../../../prompts/profile/chapters/%s/%s.md" % (key, cid)))

    lines = ["// @generated by scripts/gen_profile_prompts.py — DO NOT EDIT.",
             "// Regenerate: python3 scripts/gen_profile_prompts.py", "",
             "pub const TYPE_FILES: &[(&str, &str)] = &["]
    for key, path in embed_types:
        lines.append('    ("%s", include_str!("%s")),' % (key, path))
    lines.append("];")
    lines.append("")
    lines.append("pub const CHAPTER_FILES: &[(&str, &str, &str)] = &[")
    for key, cid, path in embed_chapters:
        lines.append('    ("%s", "%s", include_str!("%s")),' % (key, cid, path))
    lines.append("];")
    lines.append("")
    write_file(EMBED, "\n".join(lines))
    print("Generated %d types, %d chapters." % (len(embed_types), len(embed_chapters)))


if __name__ == "__main__":
    main()
